services:
  server:
    build:
      context: .
      target: server-dev
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./src:/app
      - /app/.venv

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: shopy
      POSTGRES_PASSWORD: shopy
      POSTGRES_DB: shopy
      PGDATA: /var/pgdata
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/pgdata

volumes:
  pgdata:
